version: '3.8'

services:
  stock_db:
    build: stock_db
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0'
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql://fastapi_traefik:fastapi_traefik@db:5432/fastapi_traefik
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=fastapi_traefik
      - POSTGRES_PASSWORD=fastapi_traefik
      - POSTGRES_DB=fastapi_traefik

  valuation_app:
    build: valuation
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python main.py'
    environment:
      - STOCK_DB_URL=stock_db
      - STOCK_DB_PORT=8000

    
volumes:
  postgres_data:
  