version: '3.8'

services:
  stock_db:
    build: stock_db
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0'
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - REST_API_USER=${REST_API_USER}
      - REST_API_PASSWORD=${REST_API_PASSWORD}
      - REST_API_PASSWORD_HASHED=${REST_API_PASSWORD_HASHED}
      - SECRET_KEY_JWT=${SECRET_KEY_JWT}
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  valuation_app_sp500:
    build: valuation
    command: >
      bash -c "while !</dev/tcp/stock_db/8000; do sleep 1; done;
      python3 main.py --indexName SP500 --addToDatabase True --verbose True --scheduled True"
    environment:
      - STOCK_DB_URL=stock_db
      - STOCK_DB_PORT=8000
      - REST_API_USER=${REST_API_USER}
      - REST_API_PASSWORD=${REST_API_PASSWORD}
    depends_on:
      - stock_db

  valuation_app_dax:
    build: valuation
    command: >
      bash -c "while !</dev/tcp/stock_db/8000; do sleep 1; done;
      python3 main.py --indexName DAX --addToDatabase True --verbose True --scheduled True"
    environment:
      - STOCK_DB_URL=stock_db
      - STOCK_DB_PORT=8000
      - REST_API_USER=${REST_API_USER}
      - REST_API_PASSWORD=${REST_API_PASSWORD}
    depends_on:
      - stock_db
  
  cherry-picker:
    build: cherry_picker
    command: >
      bash -c "while !</dev/tcp/stock_db/8000; do sleep 1; done;
      python3 main.py"
    environment:
      - STOCK_DB_URL=stock_db
      - STOCK_DB_PORT=8000
      - REST_API_USER=${REST_API_USER}
      - REST_API_PASSWORD=${REST_API_PASSWORD}
      - SP500_WEBHOOK=${SP500_WEBHOOK}
      - DAX_WEBHOOK=${DAX_WEBHOOK}
    depends_on:
      - stock_db

volumes:
  postgres_data:
  